apiVersion: v2
name: hostel-open-webui
description: Internal Open WebUI access frontend for Hostel on Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: open-webui
    version: 8.19.0
    repository: https://helm.openwebui.com
