{{- if and .Values.grafana.enabled (not .Values.grafana.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hostel-tooling.grafanaFullname" . }}
  labels:
    {{- include "hostel-tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
stringData:
  {{ .Values.grafana.admin.userKey }}: {{ .Values.grafana.admin.user | quote }}
  {{ .Values.grafana.admin.passwordKey }}: {{ .Values.grafana.admin.password | quote }}
{{- end }}
