{{- if and .Values.loki.enabled .Values.loki.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hostel-tooling.lokiFullname" . }}
  labels:
    {{- include "hostel-tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.persistence.size }}
  {{- if .Values.loki.persistence.storageClass }}
  storageClassName: {{ .Values.loki.persistence.storageClass }}
  {{- end }}
{{- end }}
