{{- if and .Values.promtail.enabled .Values.loki.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hostel-tooling.promtailFullname" . }}
  labels:
    {{- include "hostel-tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hostel-tooling.promtailFullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hostel-tooling.promtailFullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
