{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hostel-tooling.prometheusFullname" . }}
  labels:
    {{- include "hostel-tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    {{- include "hostel-tooling.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.service.port }}
      targetPort: http
{{- end }}
