{{- if and .Values.promtail.enabled .Values.promtail.serviceAccount.create .Values.loki.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hostel-tooling.promtailFullname" . }}
  labels:
    {{- include "hostel-tooling.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
  {{- with .Values.promtail.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
